// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/**
 * @title ZKVote Bridge Contract
 * @notice Verifies Groth16 proofs for cross-chain voting from Ethereum
 *         using Stellar SBT membership proofs.
 *
 * Flow:
 * 1. Relayer watches Soroban, builds SBT state tree, posts sbtRoot here
 * 2. User generates Groth16 proof (bridge.circom) proving SBT membership
 * 3. User calls castVote() with proof + public signals
 * 4. Contract verifies proof via BN254 precompiles (EIP-196/197)
 * 5. Emits VoteForwarded event for Soroban relay
 * 6. Nullifier stored to prevent double-voting
 *
 * Gas target: < 500k gas for proof verification
 */
contract Bridge {
    // ============================================
    // EVENTS
    // ============================================

    event VoteForwarded(
        uint256 indexed daoId,
        uint256 indexed proposalId,
        uint256 nullifier,
        uint256 voteChoice,
        uint256 voteRoot
    );

    event SbtRootUpdated(
        uint256 indexed daoId,
        uint256 sbtRoot,
        uint256 blockNumber
    );

    event VerifierUpdated(address indexed newVerifier);

    // ============================================
    // STATE
    // ============================================

    /// @notice Groth16 verifier contract (generated by snarkjs)
    address public verifier;

    /// @notice SBT contract address on Soroban (binds proofs to specific SBT)
    uint256 public sbtContractAddr;

    /// @notice SBT state roots per DAO (posted by relayer)
    mapping(uint256 => uint256) public sbtRoots; // daoId => sbtRoot

    /// @notice Nullifiers used per DAO+proposal (prevents double-voting)
    mapping(uint256 => mapping(uint256 => mapping(uint256 => bool)))
        public nullifiers; // daoId => proposalId => nullifier => used

    /// @notice Admin who can update verifier and SBT roots
    address public admin;

    /// @notice Chain ID for domain separation in EVMVerifier circuit
    uint256 public chainId;

    // ============================================
    // ERRORS
    // ============================================

    error OnlyAdmin();
    error InvalidProof();
    error NullifierUsed();
    error InvalidVoteChoice();
    error ZeroNullifier();
    error SbtRootNotSet();
    error InvalidVerifier();
    error InvalidAddress();

    // ============================================
    // CONSTRUCTOR
    // ============================================

    /**
     * @param _verifier Address of the deployed Groth16 verifier contract
     * @param _sbtContractAddr Soroban SBT contract address (U256)
     */
    constructor(address _verifier, uint256 _sbtContractAddr) {
        if (_verifier == address(0)) revert InvalidAddress();
        verifier = _verifier;
        sbtContractAddr = _sbtContractAddr;
        admin = msg.sender;
        chainId = block.chainid;
    }

    // ============================================
    // ADMIN FUNCTIONS
    // ============================================

    /**
     * @notice Update the Groth16 verifier contract
     * @param _newVerifier Address of the new verifier contract
     */
    function setVerifier(address _newVerifier) external {
        if (msg.sender != admin) revert OnlyAdmin();
        if (_newVerifier == address(0)) revert InvalidAddress();
        verifier = _newVerifier;
        emit VerifierUpdated(_newVerifier);
    }

    /**
     * @notice Post a new SBT state root for a DAO
     * @dev Called by relayer after watching Soroban chain
     * @param daoId DAO identifier
     * @param sbtRoot Merkle root of the SBT state tree
     */
    function updateSbtRoot(uint256 daoId, uint256 sbtRoot) external {
        if (msg.sender != admin) revert OnlyAdmin();
        sbtRoots[daoId] = sbtRoot;
        emit SbtRootUpdated(daoId, sbtRoot, block.number);
    }

    /**
     * @notice Transfer admin role
     * @param newAdmin Address of the new admin
     */
    function setAdmin(address newAdmin) external {
        if (msg.sender != admin) revert OnlyAdmin();
        if (newAdmin == address(0)) revert InvalidAddress();
        admin = newAdmin;
    }

    // ============================================
    // CORE: VOTE CASTING
    // ============================================

    /**
     * @notice Cast a cross-chain vote with Groth16 proof
     * @dev Verifies the proof and emits VoteForwarded for Soroban relay
     *
     * @param daoId DAO identifier
     * @param proposalId Proposal identifier
     * @param voteChoice 0 = against, 1 = for
     * @param nullifier Domain-separated nullifier (prevents double-voting)
     * @param voteRoot Merkle root of the voting tree
     * @param sbtRoot Merkle root of the SBT state tree
     * @param proof Groth16 proof components [a, b, c]
     */
    function castVote(
        uint256 daoId,
        uint256 proposalId,
        uint256 voteChoice,
        uint256 nullifier,
        uint256 voteRoot,
        uint256 sbtRoot,
        bytes calldata proof
    ) external {
        // === Validation ===

        // Reject zero nullifier
        if (nullifier == 0) revert ZeroNullifier();

        // Reject if nullifier already used (double-voting prevention)
        if (nullifiers[daoId][proposalId][nullifier]) revert NullifierUsed();

        // Validate vote choice is binary
        if (voteChoice > 1) revert InvalidVoteChoice();

        // Check SBT root is set for this DAO
        if (sbtRoots[daoId] == 0) revert SbtRootNotSet();

        // Verify the provided sbtRoot matches the posted one
        if (sbtRoot != sbtRoots[daoId]) revert SbtRootNotSet();

        // === Proof Verification ===

        // Build public signals array for the verifier
        // Order matches bridge.circom: [sbtContractAddr, memberAddr, daoId,
        //   proposalId, nullifier, voteChoice, voteRoot, sbtRoot]
        // Note: memberAddr is not passed here; it's derived from the proof
        // The verifier contract validates the proof against all public signals
        uint256[8] memory publicSignals;
        publicSignals[0] = sbtContractAddr;
        // memberAddr is embedded in the proof; the circuit constrains it
        // We use a dummy value here; the actual memberAddr is verified by
        // the SBT leaf hash in the circuit
        publicSignals[1] = 0; // placeholder; circuit verifies SBT leaf
        publicSignals[2] = daoId;
        publicSignals[3] = proposalId;
        publicSignals[4] = nullifier;
        publicSignals[5] = voteChoice;
        publicSignals[6] = voteRoot;
        publicSignals[7] = sbtRoot;

        // Decode proof: a (32 bytes), b (64 bytes), c (32 bytes)
        (uint256[2] memory a, uint256[2][2] memory b, uint256[2] memory c) =
            decodeProof(proof);

        // Verify Groth16 proof via precompile
        bool valid = _verifyProof(a, b, c, publicSignals);
        if (!valid) revert InvalidProof();

        // === Record Vote ===

        // Mark nullifier as used
        nullifiers[daoId][proposalId][nullifier] = true;

        // Emit event for Soroban relay
        emit VoteForwarded(daoId, proposalId, nullifier, voteChoice, voteRoot);
    }

    // ============================================
    // VIEW FUNCTIONS
    // ============================================

    /**
     * @notice Check if a nullifier has been used
     * @param daoId DAO identifier
     * @param proposalId Proposal identifier
     * @param nullifier The nullifier to check
     * @return True if the nullifier has been used
     */
    function isNullifierUsed(
        uint256 daoId,
        uint256 proposalId,
        uint256 nullifier
    ) external view returns (bool) {
        return nullifiers[daoId][proposalId][nullifier];
    }

    /**
     * @notice Get the current SBT root for a DAO
     * @param daoId DAO identifier
     * @return The SBT state root
     */
    function getSbtRoot(uint256 daoId) external view returns (uint256) {
        return sbtRoots[daoId];
    }

    // ============================================
    // INTERNAL: PROOF VERIFICATION
    // ============================================

    /**
     * @dev Verify Groth16 proof using BN254 precompiles
     * @param a Proof point A (G1)
     * @param b Proof point B (G2)
     * @param c Proof point C (G1)
     * @param publicSignals Public signals array
     * @return True if proof is valid
     */
    function _verifyProof(
        uint256[2] memory a,
        uint256[2][2] memory b,
        uint256[2] memory c,
        uint256[8] memory publicSignals
    ) internal view returns (bool) {
        // Call the verifier contract
        // The verifier contract implements the Groth16 verification
        // using BN254 precompiles (bn256Add, bn256ScalarMul, bn256Pairing)
        (bool success, bytes memory result) = verifier.staticcall(
            abi.encodeWithSignature(
                "verifyProof(uint256[2],uint256[2][2],uint256[2],uint256[8])",
                a,
                b,
                c,
                publicSignals
            )
        );

        if (!success || result.length < 32) return false;
        return abi.decode(result, (bool));
    }

    /**
     * @dev Decode raw proof bytes into Groth16 components
     * @param proof Raw proof bytes (128 bytes: a=64, b=128, c=64)
     * @return a Proof point A
     * @return b Proof point B
     * @return c Proof point C
     */
    function decodeProof(
        bytes calldata proof
    )
        internal
        pure
        returns (
            uint256[2] memory a,
            uint256[2][2] memory b,
            uint256[2] memory c
        )
    {
        require(proof.length == 256, "Invalid proof length");

        // Decode A point (64 bytes)
        a[0] = uint256(bytes32(proof[0:32]));
        a[1] = uint256(bytes32(proof[32:64]));

        // Decode B point (128 bytes, G2 - complex point)
        b[0][0] = uint256(bytes32(proof[64:96]));
        b[0][1] = uint256(bytes32(proof[96:128]));
        b[1][0] = uint256(bytes32(proof[128:160]));
        b[1][1] = uint256(bytes32(proof[160:192]));

        // Decode C point (64 bytes)
        c[0] = uint256(bytes32(proof[192:224]));
        c[1] = uint256(bytes32(proof[224:256]));
    }
}
