pragma circom 2.0.0;

include "node_modules/circomlib/circuits/poseidon.circom";

// EVM-compatible Groth16 Verifier Adapter
//
// This circuit wraps the bridge circuit's public outputs and produces
// a verification hash that can be checked on EVM using the exported
// Solidity verifier (Verifier.sol generated by snarkjs).
//
// Usage:
// 1. Compile bridge.circom to get the R1CS and verification key
// 2. Use snarkjs to generate the Solidity verifier from the VK
// 3. Deploy Verifier.sol + Bridge.sol on EVM
// 4. User generates a proof using bridge.circom's WASM witness generator
// 5. EVM bridge contract calls Verifier.verifyProof() to verify
//
// This circuit provides an additional layer:
// - Outputs a domain-separated verification hash
// - Enables cross-chain state binding
template EVMVerifier() {
    // Public inputs (passed through from bridge circuit)
    signal input sbtContractAddr;
    signal input memberAddr;
    signal input daoId;
    signal input proposalId;
    signal input nullifier;
    signal input voteChoice;
    signal input voteRoot;
    signal input sbtRoot;

    // EVM-specific: chain ID for domain separation
    signal input chainId;

    // Compute verification hash: Poseidon(all public inputs + chainId)
    // This binds the proof to a specific EVM chain
    component verifierHasher = Poseidon(9);
    verifierHasher.inputs[0] <== sbtContractAddr;
    verifierHasher.inputs[1] <== memberAddr;
    verifierHasher.inputs[2] <== daoId;
    verifierHasher.inputs[3] <== proposalId;
    verifierHasher.inputs[4] <== nullifier;
    verifierHasher.inputs[5] <== voteChoice;
    verifierHasher.inputs[6] <== voteRoot;
    verifierHasher.inputs[7] <== sbtRoot;
    verifierHasher.inputs[8] <== chainId;

    signal output verificationHash;
    verificationHash <== verifierHasher.out;

    // Verify vote choice is binary
    voteChoice * (voteChoice - 1) === 0;

    // Verify nullifier is non-zero (reject trivial proofs)
    // This is enforced by the poseidon hash producing non-zero output
    // for non-trivial inputs
}

// Main template for EVM verification
// The Solidity verifier is generated from this circuit's verification key
component main {public [
    sbtContractAddr, memberAddr, daoId, proposalId,
    nullifier, voteChoice, voteRoot, sbtRoot, chainId
]} = EVMVerifier();
